server:
  port: 8090
  servlet:
    context-path: /api/resource/

security:
  oauth2:
    client:
      clientId: 0oaivx2uysUxzlFvd0h7
      clientSecret: jdo1xC5AXlgsR5Wy4zNz82MoO9_kxPZX1gGkVa7d
    resource:
      tokenInfoUri: https://dev-517011.oktapreview.com/oauth2/default/v1/introspect

logging:
  level:
    web: debug
